/*
auto-generated by: https://github.com/pmndrs/gltfjsx
author: Vinny Passmore (https://sketchfab.com/HPrendering)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/eye-blend-a8259f43d41e4204a7e9746dfd112c30
title: Eye Blend
*/
import React, { useRef } from 'react'
import { useGLTFLoader } from '@react-three/drei/loaders/useGLTFLoader'

export default function RedEyeModel(props) {
  const group = useRef()
  const { nodes, materials } = useGLTFLoader('/red_eye_model.gltf')
  return (
    <group ref={group} {...props}>
      <group rotation={[-Math.PI / 2, 0,  Math.PI]} scale={props.scale}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, -2.82]} rotation={[0, 0, 0]} scale={[123.88, 123.88, 123.88]}>
            <mesh material={materials.Iris_001_Material} geometry={nodes.Iris_Iris_001_Material_0.geometry} />
          </group>
          <group rotation={[0, 0, 0]} scale={[120.46, 120.46, 120.46]}>
            <mesh material={materials.Sclera_001_Material} geometry={nodes.Sclera_Sclera_001_Material_0.geometry} />
          </group>
          <group position={[0, 590.11, 0]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0.74, -823.11, 2.02]} rotation={[0, 0, Math.PI]} scale={[100, 100, 100]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0.74, 12.63, 1338.75]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[100, 100, 100]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0.74, 12.63, -1212.78]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[100, 100, 100]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
        </group>
      </group>
    </group>
  )
}

